-- mod-papota-spherier — optional hook for the Mythic+ Lua mod (Mythic_Server.lua).
--
-- Spherite is awarded for a completed Mythic+ run through the module's console
-- command `.spherier points source mythique_plus <tier> <player>`. The amounts
-- live in the world table papota_sphere_point_source (source 'mythique_plus',
-- value = key tier, 150 + 50 x tier by default, timer failed included).
--
-- Paste this block in Mythic_Server.lua, in the end-of-run handler, at the point
-- where the mod iterates over the group members that completed the run. In the
-- Papota server it sits right after SetEndOfRunUnitFlags(member), with
-- `bossTracker.tier` holding the key tier of the run. Adapt the two names to
-- your version of the mod.
--
--     -- Papota : Spherite for the sphere grid (mod-papota-spherier). The scale
--     -- lives in papota_sphere_point_source (source mythique_plus, value = tier)
--     -- and the C++ module resolves it through its dedicated console command.
--     -- Player bots have no sphere state: they are not even presented.
--     if not member:IsBot() then
--         RunCommand(string.format("spherier points source mythique_plus %d %s",
--             bossTracker.tier, member:GetName()))
--     end
--
-- `member:IsBot()` exists only with mod-playerbots (ALE/Eluna binding); without
-- bots, drop the condition and keep the RunCommand line alone.
